### ISSUE TITLE
在浏览器用不会怕跨域限制吗？

### ISSUE THREAD

**Issue by weituotian** [Selection-Translator/translation.js#11]
应该只能用在nodejs和做chrome插件中，
用在自己的web项目中不能跨域ajax

**Comment by lmk123** [comment]
是的，只能在 nodejs 和 chrome 插件中使用。

**Comment by weituotian** [comment]
@lmk123 你的readme很误导人啊

**Comment by lmk123** [comment]
之前的 README 是有提到这一点的，但是在一次重构之后，我不小心把这段提示给删了 https://github.com/Selection-Translator/translation.js/commit/2bb0b8df4ee0f8bde9258ddcd3e793e35d7268a4 :joy:

有空我把这段跨域的提示加上吧
