### ISSUE TITLE
NPM 上的文件未更新

### ISSUE THREAD

**Issue by u3u** [Selection-Translator/translation.js#13]
这里导致 `apiRoot` 为 `undefined` 建议发布一个新版本
https://npm.runkit.com/translation.js/libs/APIs/google.js?t=1504087686705

``` diff
- .get(this.apiRoot + '/translate_a/single')
+ .get(that.apiRoot + '/translate_a/single')
```

还有我发现 `package.json` 中的 `main` 属性指向的是 `libs/index.js` 而不是 `dist/translation.js`

**Comment by u3u** [comment]
与 #6 重复了 0.0

**Comment by lmk123** [comment]
刚发布了一版 0.4.1

在 Node.js 或 Webpack 环境下是需要将 `main` 指向 `libs/index.js` 的，`dist` 里打包好的文件仅供直接用 `<script>` 标签引用的情况使用。

另外我一直准备重写一波的然而一直没有填这个坑 23333
