### ISSUE TITLE
谷歌翻译接口相关

### ISSUE THREAD

**Issue by miaolq** [Selection-Translator/translation.js#18]
请教下，免费情况下，谷歌翻译TKK如何做到定时修改？

**Comment by lmk123** [comment]
谷歌的 TKK 每一小时会修改一次，所以只要判断 TKK 过期了，就重新去谷歌网页翻译的网页上获取一次。

相关源码在这里：

https://github.com/Selection-Translator/translation.js/blob/89e06055b79a306c25ce3cb3104382d208587dbe/src/google-token.ts#L65-L79

代码参考了 [matheuss/google-translate-token](https://github.com/matheuss/google-translate-token) 这个项目。
