### ISSUE TITLE
发现一个bug？

### ISSUE THREAD

**Issue by yygcom** [Selection-Translator/translation.js#20]
获取到的谷歌.com的语音地址，如果用 audio标签，同时如果不是本地文件而是url页面的话会带上ref信息，导致404错误
![xxqq 20171124100014](https://user-images.githubusercontent.com/4178265/33192547-477bfaa2-d0fe-11e7-8a12-f3815d6a19c7.png)

**Comment by lmk123** [comment]
这是谷歌翻译的限制，我一会儿在 README.md 里面添加一段说明。
