### ISSUE TITLE
百度翻译失效？

### ISSUE THREAD

**Issue by magicknight** [Selection-Translator/translation.js#23]
tjs.translate({
                text：  '世界上最好听的钢琴曲',
                api: 'baidu',
                from: 'zh-CN',
                to: 'en',
            })

{ text: '世界上最好听的钢琴曲',
  raw: { error: 997, from: 'zh', to: 'en', query: '世界上最好听的钢琴曲' },
  link: 'https://fanyi.baidu.com/#auto/auto/%E4%B8%96%E7%95%8C%E4%B8%8A%E6%9C%80%E5%A5%BD%E5%90%AC%E7%9A%84%E9%92%A2%E7%90%B4%E6%9B%B2',
  from: undefined,
  to: undefined }

**Comment by lmk123** [comment]
是的，百度更改了接口，这是已知问题。新接口的代码其实已经写好了但是没充分测试过所以暂时没发出来。
