### ISSUE TITLE
没有超时的错误❌

### ISSUE THREAD

**Issue by chinanf-boy** [Selection-Translator/translation.js#31]
##  超时错误`ERROR_CODE.NETWORK_TIMEOUT`除了定义, 但没有触发过

**Comment by lmk123** [comment]
是的，目前对接口的查询没有做超时限制，开发时我考虑过添加一个超时参数，这个错误类型也因此先被定义在了代码里，但到了现在我还没有加入超时参数 😂

**Comment by lmk123** [comment]
我开了一个新 issue，未来会加入一个 timeout 参数 #32
