### ISSUE TITLE
有道翻译只能翻译文本的一部分

### ISSUE THREAD

**Issue by elliottzheng** [Selection-Translator/translation.js#35]
今天有道的接口貌似出了点问题，用有道的接口，一大段英文，只能翻译一句中文，
![图片](https://user-images.githubusercontent.com/22427645/54475585-ba6dd880-482d-11e9-813c-6d497eefc7b9.png)
同样的文本贴到网页版有道
![图片](https://user-images.githubusercontent.com/22427645/54475556-724eb600-482d-11e9-87ee-9a4e44c25849.png)
中文好像没有发现这个问题
![图片](https://user-images.githubusercontent.com/22427645/54475628-66afbf00-482e-11e9-8caf-189b49b82ab0.png)
测试代码
```js
youdao.translate({text:"Greatly simplify the steps required for translation, just copy the text to the clipboard, and wait to view the translation results in the next second"}).then(r=>console.log(r)).catch(e=>console.log(e))
```

**Comment by a631807682** [comment]
同样的问题。

**Comment by lmk123** [comment]
刚才发布了 v0.7.6 修复了这个问题，试一下

**Comment by a631807682** [comment]
试了一下，没什么问题。
