### ISSUE TITLE
使用google报错

### ISSUE THREAD

**Issue by codexu** [Selection-Translator/translation.js#48]
其他两个没什么问题，刚刚出现这个问题，以前是正常的

**Comment by lmk123** [comment]
我试了一下，谷歌国内和国外都是正常的，你是报了什么错？

**Comment by codexu** [comment]
<img width="1066" alt="截屏2019-10-1715 54 04" src="https://user-images.githubusercontent.com/15899990/66989135-5c241380-f0f6-11e9-860c-e23a763d52fb.png">

**Comment by lmk123** [comment]
index.js里代码是什么？

**Comment by lmk123** [comment]
把能重现问题的相关信息一次性说完啊，我一点一点挤牙膏多麻烦…

**Comment by codexu** [comment]
<img width="632" alt="截屏2019-10-1716 00 39" src="https://user-images.githubusercontent.com/15899990/66989612-45ca8780-f0f7-11e9-8ca4-2fe0213460ec.png">

**Comment by codexu** [comment]
把 google 换成youdao baidu 都没问题

**Comment by codexu** [comment]
刚测试了一下别的版本，换成0.7.0版本 google可以用了，但是youdao 又不行了

**Comment by lmk123** [comment]
我本地试了下是正常的。

出现错误有以下几种可能：

1. 可能刚好 google 的 token 没来得及刷新，这种情况重试一次就可以了
2. 可能你本地的梯子给拦截了。tjs 默认用的是国内谷歌的接口，不需要梯子就能访问，开了梯子可能反而会用不了

你可以加个 .catch，看看具体抛的是什么错，如图：

![image](https://user-images.githubusercontent.com/5035625/66990570-0e5cda80-f0f9-11e9-83dc-c6a59c7adc4f.png)

**Comment by codexu** [comment]
可能是我这边的问题，感谢
