### ISSUE TITLE
支不支持自动翻译第三方网站（英文翻译中文）

### ISSUE THREAD

**Issue by ifeihong** [Selection-Translator/translation.js#49]
我们有一个需求，就是有很多N个国外网站，我们自己用IFRAME进行连接，能否对接你的程序，自动翻译这些第三方网站？

**Comment by lmk123** [comment]
我写的这个工具只是翻译工具，要用它来翻译什么是你们在业务代码里决定的。在这个例子里你只需要把 iframe 的内容翻译一遍就行了。

**Comment by ifeihong** [comment]
iframe里面的内容是第三方网站，我不能控制，可否做到直接翻译第三方网站？
