### ISSUE TITLE
npmjs.org 代码版本和github上不一致

### ISSUE THREAD

**Issue by Debiancc** [Selection-Translator/translation.js#6]
![wechatimg12](https://cloud.githubusercontent.com/assets/3467606/22196486/5ba0d888-e188-11e6-8170-bc7e5daaa0e2.jpeg)

0.4.0版本，可是github上明明已经改成了that
NPM上还是this

**Comment by lmk123** [comment]
最近我在重构 translation.js 的时候顺便把这个问题修复了，但最近工作太忙，重构工作一直没有完成，所以也一直没有发新版本

**Comment by Debiancc** [comment]
ok,i temporary install from github

**Comment by lmk123** [comment]
已重新发了一个版本 0.4.1
